name: calcquest
description: "Aplicativo educacional para aprender Cálculo com trilhas, exercícios e acompanhamento de progresso."

publish_to: 'none'

version: 1.2.0+24

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  purchases_flutter: ^10.9.0
  purchases_ui_flutter: ^10.9.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_app_check: ^0.4.6
  google_sign_in: ^7.2.0
  in_app_update: ^5.0.0
  url_launcher: ^6.3.2
  cloud_functions: ^6.4.0
  firebase_messaging: 16.6.0
  flutter_local_notifications: ^22.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/branding/